# Generated by Django 4.2.25 on 2025-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ua', 'Український')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
