# Generated by Django 4.2.25 on 2025-10-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='novaposhta_branch',
            field=models.CharField(default='не указано', max_length=100, verbose_name='Отделение Новой Почты'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='не указан', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='не указано', max_length=100, verbose_name='ФИО'),
        ),
    ]
